### ISSUE TITLE
grpc + Cloud Run + API Gateway + Firebase Authentication 

### ISSUE THREAD

**Issue by cavator** [grpc-ecosystem/grpc-cloud-run-example#40]
I tried all possible ways.
 why this did not work?
the calls still not falling unauthenticated
even the docs explain to uses this way
[Authenticating users](https://cloud.google.com/endpoints/docs/grpc/authenticating-users#firebase)
```yaml
 type: google.api.Service
 config_version: 3
 name: "*.apigateway.PROJECT_ID.cloud.goog"
 title: User Service API
 apis:
  - name: app.GC_PROJECT_ID.User
 authentication:
  providers:
    - id: firebase
      jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
      issuer: https://securetoken.google.com/FIREBASE_PROJECT_ID
      audiences: FIREBASE_PROJECT_ID
  rules:
    - selector: "*"
      requirements:
        - provider_id: firebase

 usage:
   rules:
  - selector: app.PROJECT_ID.User.CreateUser
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.LinkUser
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.AddProvider
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.RemoveProvider
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.GetUser
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.UpdateDisplayName
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.UpdateUsername
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.UpdatePhotoUrl
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.UpdateEmail
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.AddFriend
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.RemoveFriend
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.BlockFriend
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.GetFriends
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.DeleteUser
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.GetEmailByUsername
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.SearchUser
    allow_unregistered_calls: false
  - selector: app.PROJECT_ID.User.CheckUsernameExist
    allow_unregistered_calls: false

 backend:
  rules:
    - selector: "*"
      jwt_audience: FIREBASE_PROJECT_ID
      address: grpcs://user-service-HASH-uc.a.run.app
```

the gcloud commands

```bash
 python3 -m grpc_tools.protoc  --include_imports --include_source_info --proto_path=../proto --descriptor_set_out=../proto/api_descriptor.pb --python_out=../generated_pb2 --grpc_python_out=../generated_pb2 user.proto
 gcloud api-gateway gateways delete grpc-user --location=us-central1
 gcloud api-gateway api-configs delete grpc-user-config  --api=grpc-user
 gcloud api-gateway api-configs create grpc-user-config  --api=grpc-user     --project=PROJECT_ID    --grpc-files=../proto/api_descriptor.pb,../api_config/user_api_config.yaml
 gcloud api-gateway gateways create grpc-user  --api=grpc-user  --api-config=grpc-user-config     --location=us-central1    --project=PROJECT_ID

```
